'use client'
import { Menu } from '@/app/src/components/UI/menu/Menu'

import { Sidebar } from '@/app/src/components/sidebar/Sidebar'
import '../../src/styles/global.scss'

interface Props {
  children: React.ReactNode
}

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: Props) {
  return (
    <div className="container page-container">
      <Menu />
      <main className="main">{children}</main>
      <div className="sidebar main-sidebar">
        <Sidebar title="Топ комьюнити" data={[{ title: 'React', imgUrl: '' }]} />
      </div>
    </div>
  )
}
